### ISSUE TITLE
Does pytorch3d support cuda 10.2 ? 

### ISSUE THREAD

**Issue by mimiliaogo** [nctu-eva-lab/3DV-2022#7]
Your requirements and the official repo of pytorch3d both mention using cuda11.3 to install pytorch3d, however, I don't have cuda11.3 in my server. I wonder is there any way to use cuda10.2 to install pytorch3d.

**Comment by CharlesChiuGit** [comment]
cudatoolkit is independent from system cuda. You don't need to worry about it.

**Comment by mimiliaogo** [comment]
Thanks.
