### ISSUE TITLE
The design of decoder

### ISSUE THREAD

**Issue by mimiliaogo** [nctu-eva-lab/3DV-2022#8]
The decoder takes the output of the pre-defined encoder, whose output is a one-dimensional latent feature. If we want to improve the decoder, does it mean we can only take the one-dimensional feature as input and use the linear regression? Or we can change the encoder so that the decoder can contain 2d or 3d convolution kernel?

**Comment by CharlesChiuGit** [comment]
Sure, you definitely can change the encoder arch as well.
