### ISSUE TITLE
Problem with mesh dataset loader

### ISSUE THREAD

**Issue by mimiliaogo** [nctu-eva-lab/3DV-2022#9]
There are two questions about the mesh dataloader. 
## 1. When I tried to use the load_obj function from pytorch3d, I got the following errors. 
(However, this problem seems to have no effect on the return value, so it is a minor issue.)
#### reproduce the error

```
from pytorch3d.io import load_obj
path = './model.obj'
v, f, _ = load_obj(path)
```
#### error message
```
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/mimiliaogo/anaconda3/envs/py3d/lib/python3.10/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/mimiliaogo/anaconda3/envs/py3d/lib/python3.10/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
```
## 2. The mesh object cannot be returned by dataloader
```
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'pytorch3d.structures.meshes.Meshes'>
```

**Comment by mimiliaogo** [comment]
I solve it by returning the dictionary and changing the collate function.

**Comment by CharlesChiuGit** [comment]
Yes, that's why `mesh` is bonus. Congrats!

**Comment by CharlesChiuGit** [comment]
Please close this issue if you got no further question.
